Feature/create review
junghyunwoo02/dogkingreceive pull request #2
Opened 2024-05-03 12:17 UTC by parkchowon

- 카드를 눌러서 디테일 페이지로 이동하면, localStorage에 **currentID**에 현재 누른 영화의 id값이 들어가게 했습니다.
- 별 hover, click 기능 구현했습니다.
- localStorage.set으로 review 생성했습니다! (**아직 key값은 password**)
- password 모달창, 기능까지 구현했습니다.

2024-05-03 12:43 UTC, junghyunwoo02 commented
너무 고생하셨어요!

2024-05-03 12:50 UTC, Wodud5683 commented
수고 많으셨습니다-!

2024-05-03 12:51 UTC, junghyunwoo02 approved these changes
확인했습니다!

2024-05-07 00:31 UTC, Elephant24456 commented
수고하셨습니다!

2024-05-07 00:35 UTC, youngeun0407 commented
확인했습니다~ 잘 구분해서 작성해주셔서 확인하기 수월했습니다! 감사합니다 고생하셨어요!

2024-05-07 00:43 UTC, Wodud5683 requested changes
수고하셨습니다!

2024-05-07 00:44 UTC, Wodud5683 approved these changes

2024-05-07 00:44 UTC, Cameron-86 approved these changes

2024-05-07 00:44 UTC, merged